<?php $wigzo = $this->getWigzoData(); ?>
<script>
    window.wigzo = (function (module) {
        module.ready = function () {
            module.searchStartVal = module.$("#search_mini_form input[type=text]").val();
            module.$("#search_mini_form").submit(function (e) {
                var currentval = module.$(e.currentTarget).find("input[type=text]").val();
                if (currentval == module.searchStartVal) {
                    return;
                }
                module.track("search", currentval || "");
            });
        };
        return module;
    }(window.wigzo || {}));
</script>

<?php if ($wigzo["enabled"]) { ?>
    <?php if ($wigzo["product"] != NULL) { ?>
        <meta property="wg:title"
              content="<?php echo $wigzo["product"]->getName() != null ? $wigzo["product"]->getName() : ""; ?>"/>
        <meta property="wg:productId"
              content="<?php echo $wigzo["product"]->getSku() != null ? $wigzo["product"]->getSku() : ""; ?>"/>
        <meta property="wg:description"
              content="<?php echo $wigzo["product"]->getDescription() != null ? $wigzo["product"]->getDescription() : ""; ?>"/>
        <meta property="wg:url"
              content="<?php echo $wigzo["product"]->getProductUrl() != null ? $wigzo["product"]->getProductUrl() : ""; ?>"/>
        <link rel="canonical"
              href="<?php echo $wigzo["product"]->getProductUrl() != null ? $wigzo["product"]->getProductUrl() : ""; ?>"/>
        <meta property="wg:image"
              content="<?php echo $wigzo["product"]->getImageUrl() != null ? $wigzo["product"]->getImageUrl() : ""; ?>"/>
        <meta property="wg:price" content="<?php echo $wigzo["currency"] != null ? $wigzo["currency"] : ""; ?>"/>
    <?php } ?>
    <?php if ($wigzo["browserpush"]) { ?>

        <!-- Wigzo Browser Push Support: Added by Magento Extension -->
        <?php if ($wigzo["viahttps"]) { ?>
            <script type="text/javascript">
                window.wigzo = (function (module) {
                    module.wigzoGcmAutoSubscribe = true;
                    return module;
                }(window.wigzo || {}));
            </script>

            <link rel="manifest" href="<?php echo $wigzo["subpath"]; ?>/gcm_manifest.json"/>
            <script async
                    src="<?php echo $wigzo["tracker"]; ?>/wigzopush_manager.js?orgtoken=<?php echo $wigzo["orgidentifier"]; ?>&subpath=<?php echo urlencode($wigzo["subpath"]); ?>"
                    type="text/javascript"></script>
        <?php } else { ?>
            <script type="text/javascript">
                window.wigzo = (function (module) {
                    module.httpGcmShowDialog = true;
                    return module;
                }(window.wigzo || {}));
            </script>
            <script async
                    src="<?php echo $wigzo["tracker"]; ?>/gcm_http_subscribe.js?orgtoken=<?php echo $wigzo["orgidentifier"]; ?>"
                    type="text/javascript"></script>
        <?php } ?>
        <!-- End Wigzo Browser Push Support -->

    <?php } ?>
<?php } ?>
